# Generated by Django 4.2.1 on 2023-07-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
