# Generated by Django 4.2.1 on 2023-07-06 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_detalleventa_cliente_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 4, 1, 59, 659601)),
        ),
    ]
